name: aws-hello-world
version: '0.1'
summary: AWS RoboMaker Hello World
description: |
  AWS RoboMaker application to rotate a Turtlebot3

base: core18
grade: devel 
confinement: devmode

parts:
  robot-ws:
    plugin: catkin
    source: .
    build-packages: [lsb-release]
    
apps:
  echo:
    command: rostopic echo /cmd_vel
    plugs: [network, network-bind]
    
  launch:
    command: roslaunch hello_world_robot deploy_rotate.launch
    plugs: [network, network-bind]